### ISSUE TITLE
Reloading issues

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/Orebfuscator#14]
From texxxx on Spigot:

11.02 22:16:58 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'orebfuscator4:ofc' in plugin Orebfuscator4 v4.2.1 11.02 22:16:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121] 11.02 22:16:58 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot42.jar:git-Spigot-6abac0c-9935adc] 11.02 22:16:58 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] 11.02 22:16:58 [Server] INFO Caused by: java.lang.NullPointerException 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.config.WorldReader.readWorld(WorldReader.java:194) ~[?:?] 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.config.WorldReader.readWorldByType(WorldReader.java:107) ~[?:?] 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.config.WorldReader.load(WorldReader.java:63) ~[?:?] 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.config.ConfigManager.load(ConfigManager.java:128) ~[?:?] 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.Orebfuscator.loadOrebfuscatorConfig(Orebfuscator.java:98) ~[?:?] 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.Orebfuscator.reloadOrebfuscatorConfig(Orebfuscator.java:114) ~[?:?] 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.commands.OrebfuscatorCommandExecutor.onCommand(OrebfuscatorCommandExecutor.java:134) ~[?:?] 11.02 22:16:58 [Server] INFO at com.lishid.orebfuscator.Orebfuscator.onCommand(Orebfuscator.java:145) ~[?:?] 11.02 22:16:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot42.jar:git-Spigot-6abac0c-9935adc]

Texxxxx: `this is when I try to reload the plugin`

**Comment by Aleksey-Terzi** [comment]
> 11.02 22:16:58 [Server] INFO at org.bukkit.craftbukkit.**v1_8_R3**.CraftServer.dispatchCommand(CraftServer.java:640) ~[spigot42.jar:git-Spigot-6abac0c-9935adc]

Look like they are using latest Orebfuscator with 1.8 spigot.
But we are Orebfuscator4 is working only with 1.9 and newer.

Could you please suggest where this problem is discussed? (I mean link)

**Comment by ProgrammerDan** [comment]
It was a PM to the DevotedMC account. I'll pass along the message!
