### ISSUE TITLE
can't disable world

### ISSUE THREAD

**Issue by belfedia** [DevotedMC/Orebfuscator#3]
" DisabledWorlds:
- world_the_end"

or

"DisabledWorlds: [world_the_end]"

or

"DisabledWorlds: []"

When i mvtp world_the_end

![erreur_xray](https://cloud.githubusercontent.com/assets/17900459/14704242/048fa230-07b4-11e6-8b45-74a4b13f2d88.jpg)

**Comment by Aleksey-Terzi** [comment]
This is bug.
It is fixed already (as well as crash in The End).
Could you please try [orebfuscator-4.0.5-SNAPSHOT.jar](https://github.com/lishid/Orebfuscator/releases/download/v4.0.5-alpha/orebfuscator-4.0.5-SNAPSHOT.jar) and let me know if world disabling is working ok for you now?

**Comment by Aleksey-Terzi** [comment]
I'm supposing this problem is already solved.
If no - then please re-open issue and provide details.

**Comment by belfedia** [comment]
Problem is solved, (ouf)
But command /ofc disable/enable worldname don't work :)

**Comment by connection-lost** [comment]
@belfedia That's gonna be another issue instead.

**Comment by ProgrammerDan** [comment]
I'll go ahead and open that for ya :)
