### ISSUE TITLE
Blocks on chunkborder always obfuscated

### ISSUE THREAD

**Issue by Maxopoly** [DevotedMC/Orebfuscator#5]
It seems like if a block is obfuscated and another adjacent block is not loaded, because the first is on a chunk border, it'll always assume the unloaded block is solid and will never recheck that.

This leads to tunnels with obfuscated walls, which are only updated if the player manually clicks them

http://puu.sh/oIi8C/d92be2611a.jpg

The obfuscated wall seen in that screenshot is right on the border of a chunk and was loaded from the opposite side, so the adjacent chunk was unloaded when the chunk was obfuscated.

**Comment by Aleksey-Terzi** [comment]
Thanks for clear problem description.
Will try to fix it for next release.

**Comment by Aleksey-Terzi** [comment]
Bug is reproduced and fixed.
You can get latest update either from [here](https://github.com/lishid/Orebfuscator/releases) or compile it by yourself.
I'm closing issue, but please reopen it if still any problems.

**Comment by Maxopoly** [comment]
Awesome, thanks a lot.
